/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 01-May-2024 22:05:13
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 50
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 50;
const float B[50] = {
  0.0007326174527, 0.001079884474, 0.001643151743, 0.002142431913, 0.002394242678,
   0.002187608974, 0.001325643039,-0.0003195040626,-0.002750207437, -0.00579530606,
    -0.0090823723, -0.01204310358, -0.01395735424, -0.01403498556, -0.01152775344,
  -0.005856912117, 0.003264341038,  0.01573598757,   0.0310233999,  0.04816968739,
    0.06587304175,  0.08262299746,  0.09687805921,   0.1072587892,   0.1127275676,
     0.1127275676,   0.1072587892,  0.09687805921,  0.08262299746,  0.06587304175,
    0.04816968739,   0.0310233999,  0.01573598757, 0.003264341038,-0.005856912117,
   -0.01152775344, -0.01403498556, -0.01395735424, -0.01204310358,  -0.0090823723,
   -0.00579530606,-0.002750207437,-0.0003195040626, 0.001325643039, 0.002187608974,
   0.002394242678, 0.002142431913, 0.001643151743, 0.001079884474,0.0007326174527
};
