/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 04-May-2024 16:21:51
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 50
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 50;
const float B[50] = {
  -0.005086013116,   0.0103151137, 0.007326108869, 0.007090406027, 0.007908772677,
   0.009168608114,   0.0106483344,  0.01224759128,  0.01393608004,  0.01569202356,
    0.01749093086,  0.01929449476,   0.0211109817,  0.02289863862,  0.02463648655,
    0.02631224319,  0.02788730897,   0.0293576587,  0.03068993427,  0.03187065572,
    0.03288188577,  0.03371077031,  0.03434151411,  0.03476930782,  0.03498311341,
    0.03498311341,  0.03476930782,  0.03434151411,  0.03371077031,  0.03288188577,
    0.03187065572,  0.03068993427,   0.0293576587,  0.02788730897,  0.02631224319,
    0.02463648655,  0.02289863862,   0.0211109817,  0.01929449476,  0.01749093086,
    0.01569202356,  0.01393608004,  0.01224759128,   0.0106483344, 0.009168608114,
   0.007908772677, 0.007090406027, 0.007326108869,   0.0103151137,-0.005086013116
};
